package cn.itcast.crm.domain;

// Generated 2011-1-18 16:16:10 by Hibernate Tools 3.3.0.GA

/**
 * SysDictionaryDetail generated by hbm2java
 */
public class SysDictionaryDetail implements java.io.Serializable {

	private Integer id;

	private Integer sort;
	private String remark;
	private String value;
	private String code;
	private Character sysFlag;

	
}
